config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  resources :enhancers

  root :to => 'hs_fix#index'
  get '/heise_newsfeed(.format)' => 'hs_fix#index'
  get '/de_morgen(.format)' => 'de_morgen_#index'
end

app/models/enhancer.rb
class Enhancer < ActiveRecord::Base
end

app/controllers/enhancers_controller.rb
class EnhancersController < ApplicationController
  before_action :find_enhancer, :only => :show

  def show
    @feed_url = @enhancer.feed_url
    @max_items = 50
    start_time = Time.now
    update_feed
    @feed_items = FeedItem.latest.limit(@max_items).where(feed: @feed_url)
    @cached_items_count = @feed_items.where('created_at < ?', start_time).count
    
    respond_to do |format|
      format.html
      format.rss   { render plain: render_rss_feed(@feed_items) }
    end

    cleanup_feed_items
  end

  private

  def find_enhancer
    @enhancer = Enhancer.find(params[:id])
  end

  def update_feed
    start_time = Time.now
    feed = Feedzirra::Feed.fetch_and_parse(@feed_url)
    if feed.nil?
      Rails.logger.debug "e: #{e.message}"
      return [500, "feed URL not found " + e.message]
    end

    feed_items = []
    new_items = 0
    count = 0

    feed.entries.each do |entry|
      count += 1
      feed_item = FeedItem.find_by_url(entry.url)
      Rails.logger.debug "=> processing #{entry.url}"  
      if feed_item.nil?
        feed_item = FeedItem.new(
                      feed:         @feed_url,
                      title:        entry.title,
                      url:          entry.url,
                      published_at: entry.published.to_s,
                      created_at:   Time.now.to_s,
                      content:      extract_content(entry.url))
        feed_item.save
        new_items += 1
      end
      feed_items << feed_item
    end

    Rails.logger.debug "#{count} items processed."
    Rails.logger.debug "#{new_items} new items."
  end

  def extract_content(link)
    doc = Nokogiri::HTML(open(link))
    doc.css(@enhancer.css_selector).collect do |content|
      content.to_xhtml
    end.join.gsub('href="/', 'href="http://www.heise.de/').gsub('<img src="/', '<img src="http://www.heise.de/')
  end

  def render_rss_feed(items)
    start_time = Time.now
    version = "2.0"
    content = RSS::Maker.make(version) do |m|
      m.channel.title =         @enhancer.title
      m.channel.description =   @enhancer.description
      m.channel.link =          "http://rss-tools.heroku.com/enhancers/#{params[:id]}.rss"
      items.each do |item|
        i = m.items.new_item
        i.title   = item.title
        i.link    = item.url
        i.date    = item.published_at
        i.summary = item.content
      end
    end
    Rails.logger.debug "  in #{Time.now - start_time} seconds"
    content.to_s
  end

  def cleanup_feed_items
    quoted_feed_url = ActiveRecord::Base.connection.quote(@feed_url)
    sql = "SELECT id FROM feed_items
    WHERE feed = #{quoted_feed_url}
    ORDER BY created_at DESC
    LIMIT #{@max_items}"

    top_ids = ActiveRecord::Base.connection.select_rows(sql).flatten
    FeedItem.where(feed: @feed_url).where('id NOT IN (?)', top_ids).delete_all
  end

end

app/helpers/enhancers_helper.rb
module EnhancersHelper
end

app/views/enhancers/_form.html.haml
= simple_form_for(@enhancer) do |f|
  = f.error_notification

  .inputs
    = f.input :title
    = f.input :description
    = f.input :feed_url
    = f.input :css_selector    
    = f.input :replacement_map
        

  .actions
    = f.button :submit

app/views/enhancers/edit.html.haml
%h1 Editing enhancer

= render 'form'

= link_to 'Show', @enhancer
\|
= link_to 'Back', enhancers_path

app/views/enhancers/index.html.haml
%h1 Listing enhancers

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @enhancers.each do |enhancer|
    %tr
      %td= enhancer.title
      %td= enhancer.description
      %td= link_to 'Show', enhancer
      %td= link_to 'Edit', edit_enhancer_path(enhancer)
      %td= link_to 'Destroy', enhancer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Enhancer', new_enhancer_path

app/views/enhancers/new.html.haml
%h1 New enhancer

= render 'form'

= link_to 'Back', enhancers_path

app/views/enhancers/show.html.haml
= link_to 'Edit', edit_enhancer_path(@enhancer)
\|
= link_to 'Back', enhancers_path

%p#notice= notice

%dl.dl-horizontal
  %dt
    %b Title:
  %dd= @enhancer.title
  %dt
    %b Description:
  %dd= @enhancer.description
  %dt
    %b Original feed:
  %dd= @enhancer.feed_url
  %dt
    %b Enhanced feed:
  %dd=link_to 'RSS', request.fullpath + ".rss" 

%p
  %small
    = "Showing the #{@max_items} latest entries."
    = "#{@cached_items_count} items from cache."

%dl
  = render(@feed_items) || 'No items found.'

= link_to 'Edit', edit_enhancer_path(@enhancer)
\|
= link_to 'Back', enhancers_path